language: python
python:
  - "3.6"
sudo: false

branches:
  only:
  - master
  - develop
install:
  - pip install -r scripts/requirements.txt
before_script:
  - chmod +x ./scripts/*.py
script:
  - python ./scripts/check_file_locations.py
  - python ./scripts/check_csv.py
  - python ./scripts/check_metadata.py
  - python ./scripts/build_data.py
  - python ./scripts/build_metadata.py
